### PR TITLE
Fix puppet validate warnings

### PR DESCRIPTION
**Pull request by timidri**

### CODE REVIEW

**Comment by timidri** [comment]
@dylanratcliffe @jarretlavallee @MartyEwings Could one of you take a brief look at the failing check (installing of the ffi gem) to see how we can fix it?

**Comment by MartyEwings** [comment]
strange it works locally, it may be something to do with the context of running it from github actions

**Comment by jarretlavallee** [comment]
@timidri I just opened #34 as a quick follow up that includes this fix as well. Do you mind taking a look at that PR?

For the CI failure, pdk is failing to install the gems through bundler since `make` is not installed in the container. Maybe there was a new build of the container that did not have `ffi` installed. I'll take a look today to see what I can find out.

**Comment by timidri** [comment]
> @timidri I just opened #34 as a quick follow up that includes this fix as well. Do you mind taking a look at that PR?
> 
> For the CI failure, pdk is failing to install the gems through bundler since `make` is not installed in the container. Maybe there was a new build of the container that did not have `ffi` installed. I'll take a look today to see what I can find out.

Thanks, I will take a look. In the meantime, I'm moving this PR off the draft status since the CI issue does not have to block this.

**Comment by MartyEwings** [comment]
@timidri @jarretlavallee does #34  make this extra to requirements ?

**Comment by jarretlavallee** [comment]
This was fixed in #34. Closing

**Pull request closed without merging**
