### PR TITLE
Morgan lillie

### LINKED ISSUE #2: Feature - Live Telemetry display
Description

Live Dashboard View of Telemetry from all PE infrastructure components,

Purpose

Creating a centralized view of live metrics on one server allows the Support team to more quickly analyze performance live across an entire ecosystem of servers,

Existing dashboard solutions should be consumed, a possible option is https://forge.puppet.com/modules/puppetlabs/puppet_metrics_dashboard but we should not necessarily limit to this solution if there is something better

Acceptance criteria
Displays live telemetry dashboard In a web based UI showing puppet enterprise component performance across all infrastructure components
Option to disable telemetry dashboard
Configuration parameters for the dashboard should be configured programmatically and not require manual input

### PR DESCRIPTION
**Pull request by morgan-lillie**

### CODE REVIEW

**Review by MartyEwings — CHANGES_REQUESTED** [review]
Looks good, assuming the conditional logic works!

The other piece of the exporter profile for this issue:

https://github.com/MartyEwings/RSAN/issues/2

include puppet_metrics_dashboard::profile::master::install

on all nodes this is applied too

**Comment by morgan-lillie** [comment]
Okay I'll add that in the next PR

**Review by dylanratcliffe — APPROVED** [review]
Looks fine to me assuming it works

**Comment by MartyEwings** [comment]
@morgan-lillie im happy to commit if you want to make sure it works as described?

If you add it to your test system, it should apply both classes to the primary and only 1 to the compiler

**Review by MartyEwings — APPROVED** [review]

**Pull request merged**
