### PR TITLE
Replaced test license string by a dummy one

### PR DESCRIPTION
**Pull request by timidri**

### CODE REVIEW

**Review by dylanratcliffe — APPROVED** [review]
Haha this is a good idea. Should I be scrubbing this from the history?

**Comment by timidri** [comment]
> Haha this is a good idea. Should I be scrubbing this from the history?

That would be a great idea. Happy to do this too - never done that before but eager to learn.

**Comment by dylanratcliffe** [comment]
You could try it locally. This is a good tool for that sort of thing: https://rtyley.github.io/bfg-repo-cleaner/

Might need to be made an admin in order to force push, but you should be able to at least run it locally

**Comment by MartyEwings** [comment]
should i merge or wait till we blast the history of the file away

**Comment by timidri** [comment]
> should i merge or wait till we blast the history of the file away

@dylanratcliffe What do you think? Should I force-push this branch with unwanted history surgically removed? In that case I think I would need force-push rights anyway. Or should main be force-pushed after merging this?

**Comment by dylanratcliffe** [comment]
Pretty sure you'd need force-push rights anyway since you'd be modifying commits as well as adding new ones. I reckon once you've proven it locally we probably just let you force push to main. Therefore merge this now, then wipe history later

**Pull request merged**
